services:
  - type: web
    name: custom_authentication
    env: python
    buildCommand: |
      pip install -r requirements.txt
      npm run build  # if using Tailwind
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn custom_authentication.wsgi:application
